trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-16.04'
      # mac:
      #   imageName: 'macos-10.13'
      # windows:
      #   imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '8'
      jdkArchitectureOption: x64
      jdkSourceOption: AzureStorage
    displayName: '[Config] Use - Java 8'
  - script: ./mvnw clean verify
    displayName: Build
